@startuml


map Template {
    id => PK
    question_id => FK
    name_of_survey =>
}

map Question {
    id => PK
    question =>
    description =>
}

map User {
    id => PK
    template_id => FK
    full_name => 
    username =>
    email =>
    role =>
    status =>
}

map Answer{
    id => PK
    user_id => FK 
    answer_id => FK
    question_id => FK
}

map Review {
    id => PK
    users_id => FK
    custom_template_id => FK
    answer_ids => FK 
    is_draft =>
}

map Quarter_review {
    id => PK
    review_id => FK
    period =>
}

Template --> Review::template_id
Question --> Template::question_id
Question --> Answer::question_id
Template --> User::template_id
User --> Review::user_id
Answer --> Review::answer_id
Review --> Quarter_review::review_id


@enduml